stages:
  process:
    cmd: python project\code\MonthlyVals.py
    deps:
    - project\code\MonthlyVals.py
    outs:
    - project\output\Monthly Values.csv
  prepare:
    cmd: python project\code\MonthlyComp.py
    deps:
    - project\code\MonthlyComp.py
    outs:
    - project\output\Monthly Computed.csv
  evaluate:
    cmd: python project\code\Score.py
    deps:
    - project\code\Score.py
